use bcoFIO;

INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Amaro Merico Vespucio','2001-02-02','M',2500.00,'Rua B');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Abílio Abel Garcia','2001-02-03','M',1000.00,'Rua C');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Bia Bianca Bones','2001-03-04','F',5000.25,'Rua D');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Beatriz Bertioga','2001-05-05','F',300.00,'Rua E');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Caio Cesar Cearez','2001-05-06','M',250.00,',Rua F');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Celso Cesare','2001-06-07','M',1542.36,'Rua J');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Danilo Douglas','2001-06-08','M',1524.56,'Rua K');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Denis Denilo','2001-07-09','M',5235.56,'Rua L');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Everton Evaristo','2001-07-10','M',2542.25,'Rua M');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Evanir Eva','2001-08-11','M',4523.54,'Rua N');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Fabio Fabricio','2001-08-12','M',1524.25,'Rua O');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Fabiola Fabiolo','2002-01-02','F',2554.25,'Rua P');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Geraldo Gomes','2002-10-03','M',1542.25,'Rua Q');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Helio Heliópolis','2002-01-04','M',1542.23,'Rua R');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Irineu Irene','2002-02-05','M',2523.00,'Rua S');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Jonas jackes','2002-02-05','M',2500.00,'Rua T');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Leandro Lago','2002-02-06','M',1500.00,'Rua U');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Lucio Lacio','2002-03-07','M',2500.00,'Rua V');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Lecio Licio','2002-04-08','M',1420.00,'Rua X');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Mario Mendes','2002-02-06','M',1262.00,'Rua W');
INSERT INTO Funcionario (`Nome_Func`, `Data_CadFunc`, `Sexo_Func`, `Sal_Func`, `End_Func`) VALUES('Olavo Odavlas','2002-07-07','M',1540.00,'Rua Y');

INSERT INTO TipoEnd (`Nome_TipoEnd`) VALUES('Entrega');
INSERT INTO TipoEnd (`Nome_TipoEnd`) VALUES('Faturamento');
INSERT INTO TipoEnd (`Nome_TipoEnd`) VALUES('Correspondência');
INSERT INTO TipoEnd (`Nome_TipoEnd`) VALUES('Cobrança');
INSERT INTO TipoEnd (`Nome_TipoEnd`) VALUES('Residential');
INSERT INTO TipoEnd (`Nome_TipoEnd`) VALUES('Comercial');


INSERT INTO Estado VALUES('AC','Acre');
INSERT INTO Estado VALUES('AL','Alagoas'); 
INSERT INTO Estado VALUES('AM','Amazonas');
INSERT INTO Estado VALUES('AP','Amapa');
INSERT INTO Estado VALUES('BA','Bahia'); 
INSERT INTO Estado VALUES('CE','Ceará'); 
INSERT INTO Estado VALUES('DF','Destrito Federal'); 
INSERT INTO Estado VALUES('ES','Espirito Santo');
INSERT INTO Estado VALUES('GO','Goias'); 
INSERT INTO Estado VALUES('MA','Maranhão'); 
INSERT INTO Estado VALUES('MG','Minas Gerais'); 
INSERT INTO Estado VALUES('MS','Mato Grosso do Sul'); 
INSERT INTO Estado VALUES('MT','Mato Grosso do Norte');
INSERT INTO Estado VALUES('PB','Paraíba');
INSERT INTO Estado VALUES('PE','Pernambuco'); 
INSERT INTO Estado VALUES('PI','Piauí'); 
INSERT INTO Estado VALUES('PR','Paraná');
INSERT INTO Estado VALUES('RJ','Rio de Janeiro'); 
INSERT INTO Estado VALUES('RN','Rio Grande do Norte'); 
INSERT INTO Estado VALUES('RO','Rondônia'); 
INSERT INTO Estado VALUES('RR','Roraima'); 
INSERT INTO Estado VALUES('RS','Rio Grande do Sul'); 
INSERT INTO Estado VALUES('SC','Santa Catarina');
INSERT INTO Estado VALUES('SE','Sergipe'); 
INSERT INTO Estado VALUES('SP','São Paulo'); 
INSERT INTO Estado VALUES('TO','Tocantins'); 


INSERT INTO `cidade` (`Sigla_Est`, `Nome_Cid`) VALUES('SP','Araraquara');
INSERT INTO `cidade` (`Sigla_Est`, `Nome_Cid`) VALUES('SP','Ourinhos');
INSERT INTO `cidade` (`Sigla_Est`, `Nome_Cid`) VALUES('SP','Americana');
INSERT INTO `cidade` (`Sigla_Est`, `Nome_Cid`) VALUES ('SP','Araçatuba');
INSERT INTO `cidade` (`Sigla_Est`, `Nome_Cid`) VALUES('SP','Fernandópolis');
INSERT INTO `cidade` (`Sigla_Est`, `Nome_Cid`) VALUES('SP','Jundiaí');
INSERT INTO `cidade` (`Sigla_Est`, `Nome_Cid`) VALUES('SP','Sorocaba');
INSERT INTO `cidade` (`Sigla_Est`, `Nome_Cid`) VALUES('SP','São José do Rio Preto');


INSERT INTO TipoCli (`Nome_TipoCli`) VALUES('Diamante');
INSERT INTO TipoCli (`Nome_TipoCli`) VALUES('Ouro');
INSERT INTO TipoCli (`Nome_TipoCli`) VALUES('Prata');
INSERT INTO TipoCli (`Nome_TipoCli`) VALUES('Bronze');
INSERT INTO TipoCli (`Nome_TipoCli`) VALUES('Cobre');
INSERT INTO TipoCli (`Nome_TipoCli`) VALUES('Zinco');


INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(1,'João Carlos','01011999',10000,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(1,'Daniel Souza','02021999',10000,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(1,'Helena Oliveira','03031999',9000,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(1,'Roberta Oliveira','04041999',8000,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(2,'Renata Leão','05051999',5000,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(2,'Jairo Gato','06061999',4000,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(3,'Fernando Gato','07071999',3000,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(3,'Giovanna Silva Leão','08081999',3000,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(4,'Lucas Ribeiro','09091999',2000,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(3,'Helder Leão','10101999',2000,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(2,'Olga Cristina Bonfiglioli','11111999',8000,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(1,'Maria Cristina Bonfiglioli Martins de Souza Santos','12121999',5000,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(1,'Salvador Eneas Feredico','01131999',9000,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(1,'Dolores Gerreiro Martins','02142000',8000,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(1,'Fabiana Bataglin','03152000',5000,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(2,'Aparecida Ribeiro','04162000',3000,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(3,'Reginaldo Ribeiro','05172000',4000,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(4,'Suellen M Nunes','06182000',3000,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(1,'Carlos Alberto','07192000',2000,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(2,'Roberto Arruda','08202000',1000,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(3,'Sandra Medeiros','09212000',1500,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(4,'Alice Santos','10222001',2500,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(5,'Valter Sanches','11232001',3500,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(6,'Pascoal Babiera','12242001',1525,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(1,'Lucia Bacalla','01252001',6321,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(3,'Maria Belido','02262001',5412,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(4,'Hamilton Belico','03262001',2563,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(5,'Alberto Belli','04272001',2412,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(6,'Marcia Bueno','05282001',1235,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(1,'Maria Catta','06292001',1236,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(2,'Carlos Cattaneo','07302001',1253,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(3,'Andre Caula','08312001',1524,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(4,'Fabia Dávello','09012001',1236,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(5,'Afonso Ferraro','10022001',1256,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(6,'Akemi Fukamizu','11032001',1452,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(1,'Bernadino Gomes','12042001',11785,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(2,'Regiani Hoki','01052001',1524,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(3,'Valter Koszura','02062001',1256,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(4,'Alexandre Kozeki','03072001',1225,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(5,'Vittorio Lannocca','04082001',1253,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(6,'Domingos Lanini','05092002',1253,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(1,'Paulo Mello','06102001',10000,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(2,'Zilda Mellone','07112001',8000,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(3,'Marlene Moura','08122001',3000,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(4,'Francisca Oliveira','09132001',2300,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(5,'Marlene Pereira','10142001',2562,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(6,'Milton Pereira','11152001',2563,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(1,'Ligia Ramos','12162001',9200,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(2,'Mariangela Ramos','01172001',7000,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(3,'Dora Romariz','02182001',5263,'F');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(4,'Paulino Romelli','03192001',5428,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(5,'Fernando Sampaio','04202001',2023,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(6,'José Sampaio','05212001',2235,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(1,'Vicenzo Senatori','06222001',7000,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(2,'Geraldo Senedeze','07232001',2531,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(3,'Mauro Soares','08242001',2532,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(4,'Paulo Souza','09252001',2542,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(5,'Emidio Trifoni','10262001',2563,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(6,'Heitor Vernile','11272001',2542,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(1,'Carlos Saura','12282001',6000,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(2,'Angelino Saullo','01292001',5000,'M');
INSERT INTO `cliente` (`Cod_TipoCli`, `Nome_Cli`, `Data_CadCli`, `Renda_Cli`, `Sexo_Cli`)  VALUES(3,'Aldo Savazzoni','02282001',4000,'M');


INSERT INTO Conjuge VALUES(1,'Renata',3000.00,'F');
INSERT INTO Conjuge VALUES(2,'Helena',5000.00,'F');
INSERT INTO Conjuge VALUES(3,'Daniel',6000.00,'M');
INSERT INTO Conjuge VALUES(4,'Tarcisio',1000.00,'M');
INSERT INTO Conjuge VALUES(5,'João Carlos',7000.00,'M'); 
INSERT INTO Conjuge VALUES(6,'Carla',9000.00,'M');
INSERT INTO Conjuge VALUES(7,'Ana Lucia',3000.00,'F');


INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(1,1,1,'Rua Soraia - 29','Vila Santana',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(2,1,1,'Rua Macunaima - 192','Jd.Europa',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(1,1,2,'Rua Mariá - 342','Jd. Araguaia','Apto. 23');
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(2,2,2,'Rua Juca - 542','Vila Catarina ','Apto. 2');
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(2,2,3,'Pça Marcondes - 542','Vila Tereza ',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(3,1,4,'Rua Santa Catarina - 1342','Vila Osvaldo Cruz',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(1,1,1,'Av. Imirim, 325','Vila Vilma',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(1,1,2,'Rua Clélia, 456','Vila Zoraide',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(1,1,3,'Rua Pio XI, 938','Jd. América',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(2,1,4,'Travessa 15, 1200','Vila Sonia',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(2,2,5,'Av. Sodré, 392','Jd. Carnaúba',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(2,3,6,'Av Mutinga, 200','Parque das Flores',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(3,2,7,'Rua Cons. Ribas 594','Parque Municipal',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(3,2,8,'Rua Maria Belido', 'Parque Industrial',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(3,2,9,'Rua Avai 164','Vila Maria',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(4,2,10,'Rua Bororós, 67','Vila Santa Terezinha',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(4,2,11,'Rua Jose Pereira, 340','Zona da Mata',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(4,3,12,'Av. Casa Verde, 450','Jd. Botucatu',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(4,4,13,'Av Dr Gouveia, 392','Jd. Moricatupotá',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(5,3,14,'Rua Lucena 184','Jd. Canhem BaBa',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(5,3,15,'Av. Indianópolis 593','Vila Angela',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(5,3,16,'Rua Alexandre Duma 486','Parque Piributa',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(6,3,17,'Rua Maria Júlia 1207','Jd. Americanópolis',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(6,3,18,'Rua Afonso Meira, 948','Parque Cruzeiro do Sul',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(6,3,19,'Rua Bela Cintra 392','Vila Saturno',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(6,4,20,'Rua Basilio 199','Jardim Jupter',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(1,4,21,'Rua Doce 32','Praça Marte',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(1,4,22,'Rua Grumix 114','Largo de Netuno',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(1,4,23,'Rua Emilia 32','Area de Plutão',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(1,4,24,'Al Jurupis 900','Vila Lua Branca',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(1,4,25,'Av. Guedes 653','Parque Urano',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(2,5,26,'Rua Neves 430','Jd. Paraiso',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(2,5,27,'Av. Mario Zonta, 180','Terra Prometida',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(2,5,28,'Rua Florida, 430','Jd. das Flores',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(3,5,29,'Av. Jose Barroso, 305','Praça das Margaridas',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(3,5,30,'Rua Mirina, 38','Zona Franca',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(4,5,31,'Rua Iagaraí, 46','Jd. Brasileiro',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(4,5,32,'Rua Paulista, 251','Jd. MMDC',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(4,2,33,'Rua Salete, 320','Jd. Sales Garcia',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(5,1,34,'Rua Souza, 115','Vila Sonia',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(5,1,35,'Rua Alcion, 604','Parque Piraque',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(5,1,36,'Av. Sabará, 987','Parque Piqueri',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(6,2,37,'Rua Oscar Freire, 453','Parque Infantil',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(6,2,38,'Av. Amaral Gama, 58','Jardim Judas',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(6,2,39,'Rua Iru, 23','Jd. São Salvador',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(1,2,40,'Rua Silvia, 560','Vila Pau Brasil',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(1,2,41,'Rua Moura, 147','Vila Viela',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(1,3,42,'Rua Aroeir, 954','Vila Amarela',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(1,3,43,'Rua Pereira, 394','Vila Verde',null);
INSERT INTO `endereco` (`Cod_TipoEnd`, `Cod_Cid`, `Cod_Cli`, `Nome_Rua`, `Nome_Bairro`, `Compl_End`)VALUES(2,3,44,'Rua Galeão, 54','Vila Branca',null);

select DATE_SUB(CURDATE(), INTERVAL 1 DAY);
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(1,1000.00,DATE_SUB(CURDATE(), INTERVAL 30 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(1,2000.00,DATE_SUB(CURDATE(), INTERVAL 29 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(1,3000.00,DATE_SUB(CURDATE(), INTERVAL 28 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(2,1000.00,DATE_SUB(CURDATE(), INTERVAL 27 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(3,1000.00,DATE_SUB(CURDATE(), INTERVAL 26 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(4,1000.00,DATE_SUB(CURDATE(), INTERVAL 25 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(5,1000.00,DATE_SUB(CURDATE(), INTERVAL 24 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(6,1000.00,DATE_SUB(CURDATE(), INTERVAL 23 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(7,1000.00,DATE_SUB(CURDATE(), INTERVAL 22 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(8,1000.00,DATE_SUB(CURDATE(), INTERVAL 21 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(9,1000.00,DATE_SUB(CURDATE(), INTERVAL 20 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(10,1000.00,DATE_SUB(CURDATE(), INTERVAL 19 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(11,1000.00,DATE_SUB(CURDATE(), INTERVAL 18 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(12,1000.00,DATE_SUB(CURDATE(), INTERVAL 17 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(13,1000.00,DATE_SUB(CURDATE(), INTERVAL 16 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(14,1000.00,DATE_SUB(CURDATE(), INTERVAL 15 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(15,1000.00,DATE_SUB(CURDATE(), INTERVAL 14 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(16,1000.00,DATE_SUB(CURDATE(), INTERVAL 13 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(17,1000.00,DATE_SUB(CURDATE(), INTERVAL 12 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(18,1000.00,DATE_SUB(CURDATE(), INTERVAL 11 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(19,1000.00,DATE_SUB(CURDATE(), INTERVAL 10 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(20,1000.00,DATE_SUB(CURDATE(), INTERVAL 9 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(21,1000.00,DATE_SUB(CURDATE(), INTERVAL 8 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(22,1000.00,DATE_SUB(CURDATE(), INTERVAL 7 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(23,1000.00,DATE_SUB(CURDATE(), INTERVAL 6 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(24,1000.00,DATE_SUB(CURDATE(), INTERVAL 5 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(25,1000.00,DATE_SUB(CURDATE(), INTERVAL 4 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(26,1000.00,DATE_SUB(CURDATE(), INTERVAL 3 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(27,1000.00,DATE_SUB(CURDATE(), INTERVAL 2 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(28,1000.00,DATE_SUB(CURDATE(), INTERVAL 1 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(29,1000.00,DATE_SUB(CURDATE(), INTERVAL 30 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(30,1000.00,DATE_SUB(CURDATE(), INTERVAL 29 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(31,1000.00,DATE_SUB(CURDATE(), INTERVAL 28 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(32,1000.00,DATE_SUB(CURDATE(), INTERVAL 27 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(33,1000.00,DATE_SUB(CURDATE(), INTERVAL 26 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(34,1000.00,DATE_SUB(CURDATE(), INTERVAL 25 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(35,1000.00,DATE_SUB(CURDATE(), INTERVAL 24 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(36,1000.00,DATE_SUB(CURDATE(), INTERVAL 23 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(37,1000.00,DATE_SUB(CURDATE(), INTERVAL 22 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(38,1000.00,DATE_SUB(CURDATE(), INTERVAL 21 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(39,1000.00,DATE_SUB(CURDATE(), INTERVAL 20 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(40,1000.00,DATE_SUB(CURDATE(), INTERVAL 19 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(41,1000.00,DATE_SUB(CURDATE(), INTERVAL 18 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(42,1000.00,DATE_SUB(CURDATE(), INTERVAL 17 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(43,1000.00,DATE_SUB(CURDATE(), INTERVAL 16 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(44,1000.00,DATE_SUB(CURDATE(), INTERVAL 15 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(45,1000.00,DATE_SUB(CURDATE(), INTERVAL 14 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(46,1000.00,DATE_SUB(CURDATE(), INTERVAL 13 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(47,1000.00,DATE_SUB(CURDATE(), INTERVAL 12 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(48,1000.00,DATE_SUB(CURDATE(), INTERVAL 11 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(49,1000.00,DATE_SUB(CURDATE(), INTERVAL 10 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(50,1000.00,DATE_SUB(CURDATE(), INTERVAL 9 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(51,1000.00,DATE_SUB(CURDATE(), INTERVAL 8 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(52,1000.00,DATE_SUB(CURDATE(), INTERVAL 7 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(53,1000.00,DATE_SUB(CURDATE(), INTERVAL 6 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(54,1000.00,DATE_SUB(CURDATE(), INTERVAL 5 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(55,1000.00,DATE_SUB(CURDATE(), INTERVAL 4 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(56,1000.00,DATE_SUB(CURDATE(), INTERVAL 3 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(57,1000.00,DATE_SUB(CURDATE(), INTERVAL 2 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(58,1000.00,DATE_SUB(CURDATE(), INTERVAL 1 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(59,1000.00,DATE_SUB(CURDATE(), INTERVAL 1 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(60,1000.00,DATE_SUB(CURDATE(), INTERVAL 2 DAY));
INSERT INTO credito (`Cod_Cli`, `Cred_Cli`, `Data_CredCli`)  VALUES(61,1000.00,DATE_SUB(CURDATE(), INTERVAL 3 DAY));

INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(1,'434-2356','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(1,'256-4578','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(1,'256-5623','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(2,'242-9865','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(2,'323-8945','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(2,'232-7845','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(3,'565-2365','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(3,'454-1254','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(3,'898-2345','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(4,'454-1223','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(4,'787-4512','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(5,'525-4578','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(5,'252-9887','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(6,'578-6521','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(6,'568-5421','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(7,'536-3254','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(8,'568-2154','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(9,'587-3221','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(10,'863-6598','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(11,'138-8754','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(12,'123-6598','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(13,'321-6357','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(14,'301-1232','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(15,'321-4512','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(16,'333-3221','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(17,'555-4578','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(18,'666-1245','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(19,'777-3265','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(20,'888-2154','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(21,'999-1111','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(21,'202-1222','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(22,'254-3333','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(23,'458-4444','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(23,'874-5555','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(24,'313-6666','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(24,'587-7777','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(25,'589-8888','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(26,'999-9999','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(27,'999-1010','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(27,'111-1111','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(28,'222-1212','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(28,'333-1313','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(28,'444-1414','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(29,'555-1515','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(29,'666-1616','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(30,'777-1717','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(31,'888-1818','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(32,'999-1919','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(33,'101-2020','015');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(34,'555-2121','021');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(35,'333-2222','021');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(36,'717-2323','021');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(37,'656-2424','021');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(38,'374-2525','021');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(39,'859-2626','021');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(40,'222-2727','021');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(41,'256-2828','021');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(42,'542-2929','021');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(43,'578-3030','021');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(44,'896-4041','021');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(45,'369-5050','021');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(46,'132-5151','021');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(47,'321-6161','021');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(48,'542-7171','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(49,'201-8181','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(50,'301-9191','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(50,'401-1919','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(50,'501-1818','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(51,'601-1212','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(52,'701-1313','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(53,'801-1414','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(54,'901-1515','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(56,'222-1616','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(56,'333-1714','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(57,'111-1818','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(58,'444-1919','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(59,'222-2020','011');
INSERT INTO fone (`Cod_Cli`, `Num_Fone`, `Num_DDD`) VALUES(62,'333-2121','011');

INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(1,'Joaobrasao@Hotmail.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(1,'Joaobrasao@bbb.com.br');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(1,'Joaobrasao@xxx.com.br');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(1,'JoaoCarloss@Globo.com.br');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(2,'DanielLeao@uol.com.br');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(3,'HOL@Hotmail.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(4,'ROL@Hotmail.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(5,'RenataLeao01@Hotmail.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(5,'Renata.Leao@Globo.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(6,'JairoGato@Bol.com.br');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(7,'FernandoLeao@Hotmil.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(8,'GiGi_Leao@Hotmial.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(9,'Lucas_Leao@Hotmail.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(10,'HelderLeão@Hotmail.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(11,'OlgaCBonfiglioli@Hotmail.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(12,'MCBMSS@Hotmail.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(13,'SEFeredico@Hotmail.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(14,'DoloresGMartins@Hotmail.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(15,'Fabiana_Bataglin@Hotmail.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(28,'Alberto_Belli@Hotmail.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(29,'Marcia_Bueno@Hotmail.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(30,'MariaCatta@Hotmail.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(38,'ValterKoszura@Hotmail.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(51,'PaulinoRomelli@Hotmail.com');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(52,'Fernando Sampaio');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(53,'JoséSampaio@uol.com.br');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(54,'VicenzoSenatori@uol.com.br');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(55,'GeraldoSenedeze@uol.com.br');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(61,'AngelinoSaullo@uol.com.br');
INSERT INTO email (`Cod_Cli`, `EMail_Cli`)  VALUES(62,'AldoSavazzoni@uol.com.br');

INSERT INTO StatusPedido VALUES(null,'Aberto');
INSERT INTO StatusPedido VALUES(null,'Pendente');
INSERT INTO StatusPedido VALUES(null,'Fechado');
INSERT INTO StatusPedido VALUES(null,'Cancelado');

INSERT INTO Dependente VALUES(null,3,'Sebastiana Maria','2010-01-01','F');
INSERT INTO Dependente VALUES(null,3,'Sebastião Mario','2010-01-01','M');
INSERT INTO Dependente VALUES(null,4,'Aurea Virtude','2010-01-01','F');
INSERT INTO Dependente VALUES(null,4,'Aureo Visture','2010-01-01','M');
INSERT INTO Dependente VALUES(null,7,'Pedro da Silva','2010-01-01','F');
INSERT INTO Dependente VALUES(null,7,'Alvares da Silva','2010-01-01','M');
INSERT INTO Dependente VALUES(null,7,'Cabral da Silva','2010-01-01','M');

INSERT INTO TipoProd VALUES(null,'Primeira Linha');
INSERT INTO TipoProd VALUES(null,'Segunda Linha');
INSERT INTO TipoProd VALUES(null,'Terceira Linha');
INSERT INTO TipoProd VALUES(null,'Quarta Linha');
INSERT INTO TipoProd VALUES(null,'Quinta Linha');

INSERT INTO Produto VALUES(null,1,'Armário Inox',1000,1200);
INSERT INTO Produto VALUES(null,1,'Armário Madeira',1000,2200);
INSERT INTO Produto VALUES(null,2,'Armário Metal',1000,200);
INSERT INTO Produto VALUES(null,1,'Mesa Vidro',100,1500);
INSERT INTO Produto VALUES(null,3,'Mesa Fórmica',1000,200);
INSERT INTO Produto VALUES(null,2,'Mesa Madeira',1000,800);
INSERT INTO Produto VALUES(null,1,'Sofa Couro',500,2200);
INSERT INTO Produto VALUES(null,2,'Sofa Napa',500,200);
INSERT INTO Produto VALUES(null,1,'Estante Madeira',500,12200);
INSERT INTO Produto VALUES(null,1,'Cama',500,1200);
INSERT INTO Produto VALUES(null,1,'Geladeira',500,3200);
INSERT INTO Produto VALUES(null,1,'Fogão',500,700);
  
/*
-- *********************************************************************************
* Verificando a Criação da Tabelas do Database           *

*/

-- *********************************************************************************
SELECT * FROM Bonus;
SELECT * FROM Cidade;
SELECT * FROM Cliente;
SELECT * FROM Conjuge;
SELECT * FROM Credito;
SELECT * FROM Dependente;
SELECT * FROM EMail;
SELECT * FROM Endereco;
SELECT * FROM Estado;
SELECT * FROM Fone;
SELECT * FROM Funcionario;
SELECT * FROM Historico;
SELECT * FROM Itens;
SELECT * FROM Parcela;
SELECT * FROM Pedido;
SELECT * FROM Pontuacao;
SELECT * FROM Produto;
SELECT * FROM StatusPedido;
SELECT * FROM TipoCli;
SELECT * FROM TipoEnd;
SELECT * FROM TipoProd;
SELECT count(1) FROM Bonus;
SELECT count(1) FROM Cidade;
SELECT count(1) FROM Cliente;
SELECT count(1) FROM Conjuge;
SELECT count(1) FROM Credito;
SELECT count(1) FROM Dependente;
SELECT count(1) FROM EMail;
SELECT count(1) FROM Endereco;
SELECT count(1) FROM Estado;
SELECT count(1) FROM Fone;
SELECT count(1) FROM Funcionario;
SELECT count(1) FROM Historico;
SELECT count(1) FROM Itens;
SELECT count(1) FROM Parcela;
SELECT count(1) FROM Pedido;
SELECT count(1) FROM Pontuacao;
SELECT count(1) FROM Produto;
SELECT count(1) FROM StatusPedido;
SELECT count(1) FROM TipoCli;
SELECT count(1) FROM TipoEnd;
SELECT count(1) FROM TipoProd;
